name=TableWiFi
version=1.0.0
author=Kevin Hoherz and Jeff Hoherz
maintainer=Kevin Hoherz
sentence=A library that controls Kevins desk
paragraph=wifi and peripheral functionality
category=Control
url=http://deck.local
architectures=esp
includes=TableWiFi.h